project:
  type: website
  output-dir: _site
  render:
    - "**/index.qmd"
    - "contact.qmd"
    - "workshops.qmd"
    - "people/*.qmd"

website:
  title: UK Centre for Ecology & Hydrology Research Software Engineers
  description: Website for the UK Centre for Ecology & Hydrology Research Software Engineering team.

  announcement:
    content: This site is a work in progress.
    type: danger
    icon: exclamation-circle
    position: below-navbar
    dismissable: true

  navbar:
    background: "#00678e"
    foreground: "#eaefec"
    right:
      - updates/index.qmd
      - projects/index.qmd
      - text: Training
        menu:
          - workshops.qmd
          - tutorials/index.qmd
      - people/index.qmd
      - contact.qmd

  page-footer: 
    center: "This website was created using the [UKCEH brand](https://github.com/ukceh-rse/brand-yml) for [Quarto](https://quarto.org/) and is hosted by [Github pages](https://pages.github.com/)."

  site-url: https://ukceh-rse.github.io
  repo-url: https://github.com/ukceh-rse.github.io
  repo-actions: [source, issue]
  repo-link-target: _blank

  open-graph:
    site-name: UKCEH-RSE

  draft-mode: visible

metadata-files:
  - _format.yml

execute:
  freeze: auto
