---
title: NetDRIVE Annual Gathering
author:
  - name: Joe Marsh Rossney
    url: "https://ukceh-rse/github.io/people/joe.html"
date: 2025-09-26
abstract: |
  Joe attended the annual gathering for the NetDRIVE project, which is focused on the long-term sustainability of digital research infrastructure.

categories: [software, community]

toc: true
---

## Introduction


The Network for sustainable Digital Research Infrastructure Vision and Expertise (NetDRIVE) is a UKRI project set up to connect various players in the DRI space (academics, software engineers, HPC managers, procurement specialists, ...) with the shared ambition to make DRI more environmentally sustainable.

I was fortunate enough to attend NetDRIVE's annual gathering in Durham, as a representative for the ongoing [Sustainable Digital Research Infrastructure project](/projects/2025_sdri.qmd), led by Kelly Widdicks at UKCEH.

Although I'm a newcomer to this area I found it thoroughly enjoyable.
It was a relatively small group and quite a packed schedule, so we got to know each other pretty well (by conference standards at least) --- usually with conferences I find that I have lots of one-off conversations and never get a chance to follow up.

Although it is the spiritual successor to the [UKRI Net Zero Digital Research Infrastructure Scoping Project](https://net-zero-dri.ceda.ac.uk/), NetDRIVE is still a young project whose scope and aims are still being refined.
One of the main tasks for this annual gathering was to establish working groups to drive forward some of the early ...

These working groups will mainly be driven forward by the NetDRIVE 'champions', who have 20% FTE funding from the project to work on aligned research activities.
**There is an open call for new NetDRIVE champions -- see here.**


